### ISSUE TITLE
Patent Valuation

### ISSUE THREAD

**Issue by SylvianHemus** [pqaidevteam/pqai#47]
Can you use Pqai for patent valuation as an AI accounting tool? Any tools like that out there? Chatgpt pulled up OceanTomo which doesn't look like an AI to me...

**Comment by mahesh-maan** [comment]
No, PQAI does not assign value scores to patents.

Few suggestions on where to look:
* One tool that assigns value to patents is [Patsnap](https://www.patsnap.com/), but you'll have to buy a subscription.
* You can also try GreyB's [ranking engine](https://panel.greyb.com/ranking/) - which is free but it only provides ranking in the same technology class. It does not provide absolute values.
* Unified patents portal also assigns a number of indexes to each patent ([example](https://portal.unifiedpatents.com/patents/patent/US-8982087-B2)). One of these, [CITX](https://support.unifiedpatents.com/hc/en-us/articles/115001550673-What-is-the-difference-between-APIX-CITX-and-BRIX), can be considered as a proxy for patent value.
