### ISSUE TITLE
No Search Results for Sample Query

### ISSUE THREAD

**Issue by raymondcarl** [pqaidevteam/pqai#54]
**Describe the bug**
When deploying locally, the results are empty for a sample query such as: http://localhost:8501/search/102/?q=fire%20fighting%20drones&lq=&type=patent&n=10

<img width="942" alt="Screenshot 2023-11-06 121317" src="https://github.com/pqaidevteam/pqai/assets/9866425/08f2871d-5b6e-46ad-b827-ebcc04757e84">

**To Reproduce**
I followed the steps in the deployment guide here: [https://github.com/pqaidevteam/pqai/wiki/Deployment]( https://github.com/pqaidevteam/pqai/wiki/Deployment)

**Expected behavior**
I was expecting to see similar results as the same search performed on [https://search.projectpq.ai/](https://search.projectpq.ai/).

**Screenshots**
Included in the respective areas.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server
 - Browser Chrome
 - Version 119

**Additional context**
From what I can see, mongoDB has been loaded correctly. The document count looks approximately correct.
![image](https://github.com/pqaidevteam/pqai/assets/9866425/32c20a5a-ce9e-4e78-a748-43c3836827dc)

One issue could be that there is not a "npl" collection in MongoDB. I'm not really sure what this is for though, but I saw it as an .env variable.

Here is my .env file. I have also tried to set SMART_INDEX_SELECTION to both 0 and 1.

MODELS_DIR=/home/***/pqai/models         # absolute path to the "models" directory
INDEXES_DIR=/home/***/pqai/indexes       # absolute path to the "indexes" directory
TOKENS_FILE=/home/***/pqai               # absolute path to the access tokens file
PQAI_S3_BUCKET_NAME=[my bucket name]   # (not needed for testing)
AWS_ACCESS_KEY_ID=[my access key]       # (not needed for testing)
AWS_SECRET_ACCESS_KEY=[my secret]  # (not needed for testing)
API_PORT=8501                        # port to be used by PQAI, default=8501
MONGO_PORT=27017                      # port for Mongo service, default=27017
MONGO_HOST=localhost                      # default=localhost
MONGO_USER=                      # leave blank if no username needed for connection
MONGO_PASSWORD=                  # leave blank if no password needed
MONGO_DBNAME=pqai                    # default=pqai
MONGO_PAT_COLL=bibliography                  # default=bibliography
MONGO_NPL_COLL=npl                  # default=npl
SMART_INDEX_SELECTION=1          # 1 or 0; set as 0 if indexes not split at subclass level
DEFAULT_SBERT_MODEL=pqai-vectorizer-v3             # any of the SBERT models present in /models directory
USE_RERANKER=0                   # 1 or 0
DISABLE_GPU=1                    # 1 or 0
SENTRY_URL=[my sentry url] # optional; leave blank is not needed
OUTGOING_EXT=0                   # 1 or 0; set as 0 for local testing
INCOMING_EXT= 0                  # 1 0r 0; set as 0 for local testing
USE_FAISS_INDEXES=1              # 1 or 0
USE_ANNOY_INDEXES=0              # 1 or 0
TOKEN_AUTHENTICATION=0           # 1 or 0; can disable for local testing

**Comment by mahesh-maan** [comment]
Hi @raymondcarl can replace the contents of your environment file with the following:

```
PQAI_S3_BUCKET_NAME=             
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
API_PORT=8501
MONGO_PORT=27017
MONGO_HOST="localhost"
MONGO_USER=
MONGO_PASSWORD=
MONGO_DBNAME="pqai"
MONGO_PAT_COLL="bibliography"
MONGO_NPL_COLL="npl"
SMART_INDEX_SELECTION=0
DEFAULT_SBERT_MODEL="pqai-vectorizer-v3"
USE_RERANKER=0
DISABLE_GPU=1
SENTRY_URL=
OUTGOING_EXT=0
INCOMING_EXT=0
USE_FAISS_INDEXES=1
USE_ANNOY_INDEXES=0
TOKEN_AUTHENTICATION=0
```

You don't need the `npl` collection in MongoDB, it's for storing non-patent data (research papers) that is optional.
