### ISSUE TITLE
Still ingesting new data?

### ISSUE THREAD

**Issue by jamesbaker1** [pqaidevteam/pqai#55]
Is this project still ingesting new patents? The search tool does not seem to populate any patents from 2023. If not, I would like to contribute!

**Comment by mahesh-maan** [comment]
Hi @jamesbaker1 there was a problem with the 2023 data. Just rebuilt the index and fixed the issue. Thanks for the offer to help, though. Much appreciated. If you'd like to contribute, please take a look at some of the [technical challenges](https://github.com/pqaidevteam/pqai/wiki/Challenges) relevant to this project and see if there is one that catches your interest.

**Comment by mahesh-maan** [comment]
Closing since this has been resolved.
