### ISSUE TITLE
Not Able to Retrive Full Patent Data

### ISSUE THREAD

**Issue by raymondcarl** [pqaidevteam/pqai#56]
**Describe the bug**

This is not necessarily a bug, but possibly just a misunderstand with the local setup instructions.

When running locally, I get an error when running this command: curl http://localhost:8501/patents/US3930271A. Patent queries work OK. I looked in the API code and can see that the server is trying to call PatentDataRequest, but I don't receive any error messages on the server side. On the client side, I only see, "server error." I think the issue is that PQAI is probably trying to invoke get_patent_data_from_s3, but there is no data on there. 

Is there a way to load the full patent data onto S3 (assuming that is where the data should be stored)?

**To Reproduce**
1. run the steps in the local deployment
2. call curl http://localhost:8501/patents/US3930271A on the command line.

**Expected behavior**

**Screenshots**
N/A

**Desktop (please complete the following information):**
Ubuntu 22.04

**Smartphone (please complete the following information):**
N/A

**Additional context**
Same request works fine using the PQAI API + token.

**Comment by mahesh-maan** [comment]
@raymondcarl I am adding an option to configure a local deployment to pull full-text from the API. Should be done in this week.

**Comment by raymondcarl** [comment]
Hi @mahesh-maan, this is working!
