### ISSUE TITLE
Please enable CORS on the API

### ISSUE THREAD

**Issue by bruffridge** [pqaidevteam/pqai#59]
**Describe the bug**
![image](https://github.com/pqaidevteam/pqai/assets/1322063/de5d2a2d-3193-472e-bf5a-f41ead20c1e1)

**To Reproduce**
1. Go to a webpage that uses javascript to send a GET request to the PQAI API endpoint in Google Chrome
2. See the CORS error in the Chrome Developer Console

**Expected behavior**
API will respond with JSON instead of throwing a CORS error.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 125

**Comment by mahesh-maan** [comment]
@bruffridge Thank you for raising this issue. I have enabled CORS on the API. Could you please try making the request again and confirm that it's working?

**Comment by bruffridge** [comment]
It is working now, thank you!

**Comment by mahesh-maan** [comment]
Thanks for confirming! Closing the issue.
